services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - finance_network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    networks:
      - finance_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  finance_network:
    driver: bridge

volumes:
  postgres_data:

